[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "https://hemocentroback.onrender.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-Forwarded-Host = "hemocentroback.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200